when:
  event: [push, pull_request]
  branch: develop
  path: ["**/*.go", ".woodpecker/test_golang.yml"]

matrix:
  GO_VERSION:
    - 1.18
    - 1.19
    - 1.20

pipeline:
  build:
    image: golang:${GO_VERSION}
    pull: true
    commands:
      - go mod download
      - go test ./...
      - go vet ./...
